friendzone_project/app/messages/__init__.py
from flask import Blueprint

# Initialises instance (routes then reference this instance)
messages_bp = Blueprint("messages", __name__)

from . import routes  # Import routes to associate them with the Blueprint

friendzone_project/app/messages/routes.py
from flask import request, render_template, session, redirect, url_for, flash

from . import messages_bp
from friendzone_project.app.messages.services import show_message_thread, show_all_messages, delete_message_thread, send_message


# Messages Home
@messages_bp.route("/")
def messages():
    # Make sure only authorised users can access this page
    if 'username' not in session:
        flash('You need to Log In or Sign Up before you can access that feature', category='error')
        return redirect(url_for('home.login'))

    result = show_all_messages([session.get('user_id')])
    session['msg_list'] = result
    return render_template('messages.html', data=result)


#Show chat
@messages_bp.route('/thread', methods=['POST'])
def full_thread():
    # Make sure only authorised users can access this page
    if 'username' not in session:
        flash('You need to Log In or Sign Up before you can access that feature', category='error')
        return redirect(url_for('home.login'))

    sender_id = request.form.get('sender_id')
    session['sender_id'] = sender_id
    result = show_message_thread(session.get('user_id'), sender_id=sender_id)
    return render_template('messages_thread.html', data=result)


@messages_bp.route("/delete", methods=['POST'])
def delete_message():
    # Make sure only authorised users can access this page
    if 'username' not in session:
        flash('You need to Log In or Sign Up before you can access that feature', category='error')
        return redirect(url_for('home.login'))

    sender = session.get('sender_id')

    rows_deleted = delete_message_thread(session.get('user_id'), sender)

    if rows_deleted > 0:
        flash(f'Message thread deleted with user: {sender}')
    else:
        flash(f'No messages found to delete with user: {sender}', category='error')

    return redirect(url_for('messages.messages'))


@messages_bp.route('/reply', methods=['POST'])
def reply():
    # Make sure only authorised users can access this page
    if 'username' not in session:
        flash('You need to Log In or Sign Up before you can access that feature', category='error')
        return redirect(url_for('home.login'))

    # Ensure messages can only be sent on an active thread
    send_to_id = request.form.get('sender_id')
    session['sender_id'] = send_to_id
    message = request.form.get('message')
    result = send_message(message, session.get('user_id'), send_to_id)

    return render_template('messages_thread.html', data=result)

friendzone_project/app/search/__init__.py
from flask import Blueprint

# Initialises instance (routes then reference this instance)
search_bp = Blueprint("search", __name__)

from . import routes  # Import routes to associate them with the Blueprint

friendzone_project/app/search/routes.py
from flask import request, render_template, session, current_app, flash, redirect, url_for

from . import search_bp
from friendzone_project.app.search.services import DataExtractor, use_location, display_search_page, find_and_format_activity, SearchSessionManager
from friendzone_project.app.extensions import _clear_session_except


# Search Page & Results
@search_bp.route("/", methods=['GET','POST'])
def search():
    if request.method == 'POST':
        try:
            # Get data from request in a usable format
            location, radius, activity, timeslot, days = DataExtractor.get_search_form_data(request)
            # Find the latitude / longitude of the location
            lat, lon = use_location(location)
            # Validate location & display search page with error if None
            if lat is None:
                return display_search_page(True)

            # Save to session for use in match functions
            SearchSessionManager.save_search_session(location, radius, activity, timeslot, days, lat, lon)

            # Remove unnecessary date from results
            formatted_results = find_and_format_activity(lat, lon, radius, activity)

            session['latest_search'] = formatted_results # Stored results to pass to match functions

            # Display results
            return render_template('results_table_template.html', data=formatted_results, activity=session['display_activity'],
                                   location=location)

        except Exception as e:
            current_app.logger.error(f"Search error : {str(e)}")
            flash(f'An unexpected error occurred. Please try again. {str(e)}', 'error')
            return display_search_page(True)

    # If GET method, display page
    # Make sure only authorised users can access this page - redirect to login page
    if 'username' not in session:
        flash('You need to Log In or Sign Up before you can access that feature', category='error')
        return redirect(url_for('home.login'))

    # Clear previously searched values
    _clear_session_except(['username', 'user_id', 'user_type'])

    # Display page with error if required - only user-defined input is Location
    return display_search_page(False)

friendzone_project/app/templates/change_password.html
{% extends "layout.html" %}

{% block centermain %}
<h4>Change Password</h4>
<hr/>



<div class="action-row">
<form action="/change_password" method="POST" class="m-5">
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">New Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="user_password">
    </div>
    <button type="submit" class="btn btn-outline-light text-dark">Change Password</button>
</form>
<div class="action-container-password">
    <h4>Passwords must be:</h4>
    <ul>
        <li class="{{ 'valid' if session.get('length_valid') else 'invalid' }}">At least 9 letters long</li>
        <li class="{{ 'valid' if session.get('upper_valid') else 'invalid' }}">At least 1 uppercase character</li>
        <li class="{{ 'valid' if session.get('lower_valid') else 'invalid' }}">At least 1 lowercase letter</li>
        <li class="{{ 'valid' if session.get('nums_valid') else 'invalid' }}"> At least 1 number</li>
    </ul>
</div>

    </div>
{% endblock centermain %}

friendzone_project/app/templates/display_links.html
{% macro display_links(user) %}

<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('home.home') }}">Home</a>
    </li>

        <!-- Added these two display links for when the user is logged in -->
    {% if session.get('username') %}

    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('search.search') }}">Search</a>
    </li>

      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('messages.messages') }}">Messages</a>
    </li>


    {% else %}

    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('home.login') }}">Log in</a>
    </li>

    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('home.signup') }}">Sign up</a>
    </li>

    {% endif %}


    {% if session.get('user_type') == 'admin' %}

    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('admin.promote') }}">Promote</a>
    </li>

    {% endif %}

    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('home.logout') }}">Log out</a>
    </li>

</ul>

{% endmacro %}

friendzone_project/app/templates/home.html
{% extends "layout.html" %}

{% block centermain %}
<h1>FriendZone</h1>
<br>

<h2>FriendZone is a labour of love by a group of extremely awesome coders.</h2>
<br>

<h4>Our hope is to banish loneliness in this busy world by making it easy to make new friends - we know it's hard as a grown up!</h4>
<br>
<br>
<p>FriendZone facilitates meetups for users in London, based on shared interests, location and availability. It bridges the online interactions we as a society have nurtured over the years by taking it offline to cherish the relationships we can build and enjoy in this beautiful city.
</p>
<br>
<p>As a potential solution to address the loneliness epidemic by encouraging high-quality social connections through entertaining activities, FriendZone aims to foster social interactions, a sense of belonging, and the growth of a community. The capital is known for its multicultural diversity among citizens and businesses, which we must emphasise and celebrate in our app. We wish to help others find their place in the largest city in Western Europe with the right company.
</p>
<br>
<p>We hope to expand to other cities after our pilot!</p>

{% endblock centermain %}

friendzone_project/app/templates/home_logged_in.html
{% extends "layout.html" %}

{% block centermain %}
<h1>WELCOME!</h1>
<br>
<br>
<br>
<h3>Time to start making friends...</h3>
<br>
<br>
<h4>Head over to Search or Messages!</h4>


{% endblock centermain %}

friendzone_project/app/templates/layout.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Title & Style -->
    <title>FriendZone</title>

    <!--     Bootstrap values, not used in my css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='fz_style.css') }}">
</head>

<body>

    {% from "display_links.html" import display_links %}
    <div class="container-fluid">


        <div class="parent">
            <div class="child child1">

                <!--         Size responsive nav bar with Logo in the top-left corner -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container">
                        <div class="logo-container">
                            <img src="{{ url_for('static', filename='friendzone_square.jpg') }}" alt="Logo"
                                class="logo">
                        </div>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            {{ display_links(user_details) }}
                        </div>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </nav>

                <!-- Main Content Block -->

                <div class="main-content">
                    <div class="container">

                        <!-- Display user_name -->
                        <div class="child child2 d-flex justify-content-between m-3">
                            <p></p>
                            {% if session.get('username') %}
                            <p class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{{ url_for('messages.messages') }}"
                                    onmouseover="this.style.color='#008080'; this.style.textDecoration='underline';"
                                    onmouseout="this.style.color='#00022e'; this.style.textDecoration='';"> User name:
                                    {{ session['username'] }}</a>

                                {% else %}
                            <p class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{{ url_for('home.login') }}"
                                    onmouseover="this.style.color='#008080'; this.style.textDecoration='underline';"
                                    onmouseout="this.style.color='#00022e'; this.style.textDecoration='';"> Username:
                                    Please log in</a>

                            </p>
                            {% endif %}

                        </div>

                        <div class="child child3 m-3">
                        </div>
                        <div class="child child4 m-3">

                            <!-- Error Messages -->
                            {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                            <ul class="flash-messages">
                                {% for category, message in messages %}
                                <li class="flash-message {{ category }}">{{ message }}</li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                            {% endwith %}
                        </div>
                        <div class="child child5 m-3">
                            <!-- Area that other html pages will display -->
                            {% block centermain %}
                            {% endblock centermain %}
                        </div>
                    </div>
                </div>
                <div class="child child6 m-3">
                </div>
                <div class="child child7 m-3">
                </div>
            </div>
            <!-- Footer -->
            <footer class="footer">
                <p class="text-center">copyright &copy; belongs to xyz</p>
            </footer>

            <!--         Bootstrap JS (optional) -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous">
                </script>
        </div>
    </div>
</body>

</html>

friendzone_project/app/templates/login.html
{% extends "layout.html" %}

{% block centermain %}
<h4>Log in page</h4>
<hr/>

{% if loginerror %}
<div class='bp-danger border border-light text-center text-light'>{{ loginerror }}</div>
{% endif %}

<form action="/login" method="POST" class="m-5">
    <div class="mb-3">
        <label for="exampleInputUserName1" class="form-label">User name</label>
        <input type="text" class="form-control" id="exampleInputUserName1" name="user_name">
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="user_password">
    </div>
    <button type="submit" class="btn btn-outline-light text-dark">Login</button>
    <button type="button" class="btn btn-outline-secondary" onclick="window.location.href='/change_password'">Forgot Password</button>
</form>
{% endblock centermain %}

friendzone_project/app/templates/logout.html
{% extends "layout.html" %}

{% block centermain %}
<h4>Log out page</h4>
<hr/>
{% endblock centermain %}

friendzone_project/app/templates/match_success.html
{% extends "layout.html" %}

{% block centermain %}

<title>Match</title>

<body>
<!-- Display two boxes with buttons -->
 <div class="action-row">

     <!-- Choose to save search -->
    <div class="action-container">
        <h2>It's a match!</h2>
        <br>
        <h2>Matched with User ID:  {{ session['matched_user'] }} </h2>

    </div>

     <!-- Choose to perform a new search -->
     <div class="action-container">
        <h2>Would you like to message this user?</h2>
         <form action="/messages/reply" method="POST">
            <input type="hidden" name="sender_id" value="{{ session['matched_user'] }}">
             <textarea name="message" placeholder="Write your reply here..." rows="4" cols="40" required></textarea>
            <button class='btn btn-sm btn-outline-success' type="submit">MESSAGE MY MATCH</button>
        </form>
    </div>
    </div>
 <br>
 <br>

<!-- Display search results in table format -->
    <h1>{{ session['display_activity'] }} in {{ location }}</h1>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Address</th>
                <th>Website</th>
                <th>Opening Hours</th>
            </tr>
        </thead>

        <tbody>
            {% for key, values in data.items() %}
            <tr>
                <td>{{ values[' '] }}</td>
                <td>{{ values['Name'] }}</td>
                <td>{{ values['Address'] }}</td>
                <td>
                    {% if values['Website'] %}
                        <a href="{{ values['Website'] }}" target="_blank">{{ values['Website'] }}</a>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td>
                    <ul>
                        {% for hours in values['Opening Hours'] %}
                        <li>{{ hours }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

{% endblock centermain %}

friendzone_project/app/templates/messages.html
{% extends "layout.html" %}

{% block centermain %}
<title>Messages</title>
<h1>Message Inbox</h1>

<body>

<br>

 <br>
 <br>

<!-- Display search results in table format -->
    <table>
        <thead>
            <tr>
                <th>From</th>
                <th>Date</th>
                <th>Message</th>
                <th>Read?</th>
                <th>Reply</th>
            </tr>
        </thead>

        <tbody>
            {% for message in data %}
            <tr>
                <td>{{ message['sender_id'] }}</td>
                <td>{{ message['date_time'].strftime('%a %d %b, %I.%M%p') }}</td>
                <td>{{ message['message'] }}</td>
                <td>{{ 'Yes' if message['isRead'] else 'No' }}</td>
                <td>
                    <form action="/messages/thread" method="POST">
                    <input type="hidden" name="sender_id" value="{{ message['sender_id'] }}">
                    <button class='btn btn-sm btn-outline-success' type="submit">Full Thread</button>
                </form>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

{% endblock centermain %}

friendzone_project/app/templates/messages_thread.html
{% extends "layout.html" %}

{% block centermain %}
<title>Messages</title>
<h1>Messages with User No: {{ session['sender_id'] }}</h1>

<body>
<!-- Display two boxes with buttons -->
 <div class="action-row">

     <!-- Choose to save search -->
    <div class="action-container">
        <h2>Would you like to delete this thread?</h2>
         <form action="/messages/delete" method="POST">
            <input type="hidden" name="sender_id" value="{{ session['sender_id'] }}">
            <button class='btn btn-sm btn-outline-danger' type="submit">DELETE</button>
        </form>
    </div>

     <!-- Choose to perform a new search -->
    <div class="action-container">
        <h2>Would you reply to this thread?</h2>
         <form action="/messages/reply" method="POST">
            <input type="hidden" name="sender_id" value="{{ session['sender_id'] }}">
             <textarea name="message" placeholder="Write your reply here..." rows="4" cols="40" required></textarea>
            <button class='btn btn-sm btn-outline-success' type="submit">REPLY</button>
        </form>
    </div>
 </div>

 <br>
 <br>

<!-- Display search results in table format -->
    <table>
        <thead>
            <tr>
                <th>From</th>
                <th>Date</th>
                <th>Message</th>
                <th>Read?</th>

            </tr>
        </thead>

        <tbody>
            {% for message in data %}
            <tr>
                <td>{{ 'You' if message['sender_id'] == session['user_id'] else message['sender_id'] }}</td>
                <td>{{ message['date_time'].strftime('%a %d %b, %I.%M%p') }}</td>
                <td>{{ message['message'] }}</td>
                <td>{{ 'Yes' if message['isRead'] else 'No' }}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

{% endblock centermain %}

friendzone_project/app/templates/no_match.html
{% extends "layout.html" %}

{% block centermain %}

<title>No Match</title>

<body>
<!-- Display two boxes with buttons -->
 <div class="action-row">

     <!-- Choose to save search -->
    <div class="action-container">
        <h2>You're the first!</h2>
        <br>
        <h2>Sorry, that means no-one else has searched for this yet. </h2>
        <br>
        <h2>But it's not the end! This search has been saved and we'll let you know when someone matches your vibe.</h2>
        <br>
        <h2>Keep an eye on your inbox, who knows when a match may appear?</h2>

    </div>

     <!-- Choose to perform a new search -->
    <div class="action-container">
        <h2>Would you like to run a new search?</h2>
        <form method="GET" action="{{ url_for('search.search') }}">
            <input type="submit" value="NEW SEARCH">
        </form>
    </div>
</div>

 <br>
 <br>

<!-- Display search results in table format -->
    <h1>{{ session['display_activity'] }} in {{ location }}</h1>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Address</th>
                <th>Website</th>
                <th>Opening Hours</th>
            </tr>
        </thead>

        <tbody>
            {% for key, values in data.items() %}
            <tr>
                <td>{{ values[' '] }}</td>
                <td>{{ values['Name'] }}</td>
                <td>{{ values['Address'] }}</td>
                <td>
                    {% if values['Website'] %}
                        <a href="{{ values['Website'] }}" target="_blank">{{ values['Website'] }}</a>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td>
                    <ul>
                        {% for hours in values['Opening Hours'] %}
                        <li>{{ hours }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

{% endblock centermain %}

friendzone_project/app/templates/promote.html
{% extends "layout.html" %}

{% block centermain %}

<h4>Admin Console</h4>
<hr/>
<table>
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Username</th>
        <th scope="col">Password</th>
        <th scope="col">Admin</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
    {% if all_users %}
    {% for user in all_users %}

    <tr>
        <th scope="row">{{user['user_id']}}</th>
        <td>{{ user['user_name'] }}</td>
        <td>{{ user['user_password'] }}</td>
        <td>{{ user['user_type'] }}</td>
        <td><a class='btn btn-sm btn-outline-success'
               href="{{url_for('admin.promote_to_admin',user_id = user['user_id'])}}">promote</a></td>
        <td><a class='btn btn-sm btn-outline-danger' href="{{url_for('admin.delete_user', user_id = user['user_id'])}}">delete</a>
        </td>

    </tr>
    {% endfor %}
    {% endif %}
    </tbody>
</table>

{% endblock centermain %}

friendzone_project/app/templates/search.html
{% extends "layout.html" %}

{% block centermain %}

<h1> Search Options</h1>

<!-- Form to take user input for Search Criteria -->
<form method="POST">

 <!-- Location Text Field -->
    <div class="form-group">
        <label for="location">Enter a Location:</label>
        <input type="text" name="location" id="location" value="{{ location }}" placeholder="Where would you like to go?">
    </div>

 <!-- Radius Dropdown Field  -->
    <div class="form-group">
      <label for="radius">Choose Radius</label>
      <select name="radius" id="radius">
        {% for option in radius %}
          <option value="{{ option.value }}" {% if option.selected %} selected {% endif %}>
            {{ option.label }}
          </option>
        {% endfor %}
      </select>
    </div>

 <!-- Activity Dropdown Field  -->
    <div class="form-group">
      <label for="activities">Choose Activity</label>
      <select name="activities" id="activities">
        {% for option in activities %}
          <option value="{{ option.value }}" {% if option.selected %} selected {% endif %}>
            {{ option.label }}
          </option>
        {% endfor %}
      </select>
    </div>

 <!-- Timeslot Dropdown Field  -->
    <div class="form-group">
      <label for="timeslots">Choose Timeslot</label>
      <select name="timeslots" id="timeslots">
        {% for option in timeslots %}
          <option value="{{ option.value }}" {% if option.selected %} selected {% endif %}>
            {{ option.label }}
          </option>
        {% endfor %}
      </select>
    </div>

  <!-- Days Dropdown Field  -->
    <div class="form-group">
      <label for="days">Choose Day(s)</label>
      <select name="days" id="days">
        {% for option in days %}
          <option value="{{ option.value }}" {% if option.selected %} selected {% endif %}>
            {{ option.label }}
          </option>
        {% endfor %}
      </select>
    </div>

  <input type="submit" value="Search">

</form>
{% endblock centermain %}

friendzone_project/app/templates/signup.html
{% extends "layout.html" %}

{% block centermain %}
<h4>Sign up page</h4>
<hr/>


<div class="action-row">
<form action="/signup" method="POST" class="m-5">
    <div class="mb-3">
        <label for="exampleInputUserEmail1" class="form-label">Email</label>
        <input type="email" class="form-control" id="exampleInputUserEmail1" name="email"> <!-- check type= email -->
    </div>

    <div class="mb-3">
        <label for="exampleInputUserName1" class="form-label">User name</label>
        <input type="text" class="form-control" id="exampleInputUserName1" name="user_name">
    </div>

    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="user_password">
    </div>

    <div class="mb-3">
        <label for="exampleInputDOB1" class="form-label">Date of birth</label>
        <input type="date" class="form-control" id="exampleInputDOB1" name="user_dob">
    </div>

    <button type="submit" class="btn btn-outline-light text-dark">Sign up</button>
</form>
<div class="action-container-password">
    <h4>Passwords must be:</h4>
    <ul>
        <li class="{{ 'valid' if session.get('length_valid') else 'invalid' }}">At least 9 letters long</li>
        <li class="{{ 'valid' if session.get('upper_valid') else 'invalid' }}">At least 1 uppercase character</li>
        <li class="{{ 'valid' if session.get('lower_valid') else 'invalid' }}">At least 1 lowercase letter</li>
        <li class="{{ 'valid' if session.get('nums_valid') else 'invalid' }}"> At least 1 number</li>
    </ul>
</div>

    </div>

{% endblock centermain %}